### ISSUE TITLE
Can't add logical lists

### ISSUE THREAD

**Issue by williambarry007** [googleads/google-api-ads-ruby#87] opened 2016-03-04 17:03 UTC
When trying to add or update logical lists, only the first rule operand is handled. For example:

    adwords = AdwordsApi::Api.new
    srv = adwords.service(:AdwordsUserListService, :v201601)
    operation = {
      :operator => 'ADD',
      :operand => {
        :xsi_type => 'LogicalUserList',
        :name => "Sample Logical List",
        :description => "Custom combination list",
        :status => 'OPEN',
        :membership_life_span => '30',
        :rules => [
          {
            :operator => 'ANY',
            :rule_operands => [
              { :xsi_type => "UserList", :id => 123456781 },
              { :xsi_type => "UserList", :id => 123456782 },
              { :xsi_type => "UserList", :id => 123456783 }
            ]
          }
        ]
      }
    }
    response = srv.mutate([operation])

The above code successfully adds the logical list, but only adds the first user list operand. It ignores any additional operands after the first one.

An update operation has the same result.

**Comment by mcloonan** [comment] 2016-03-04 17:34
Thanks for reporting.

Can you also provide the SOAP generated from this Hash? I want to see if it's an issue with how we generate the SOAP or something else.

**Comment by williambarry007** [comment] 2016-03-04 19:17
Sure, here you go (with developer token and customer ids masked):

    <?xml version="1.0" encoding="UTF-8"?>
    <env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsdl="https://adwords.google.com/api/adwords/rm/v201601" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns0="https://adwords.google.com/api/adwords/cm/v201601">
      <env:Header>
        <wsdl:RequestHeader xmlns="https://adwords.google.com/api/adwords/cm/v201601">
          <userAgent>rake (AwApi-Ruby/0.18.1, Common-Ruby/0.11.2, GoogleAdsSavon/1.0.1, ruby/2.3.0, HTTPI/2.4.1, httpclient)</userAgent>
          <developerToken>XXXXXXXXXXXXXXXXXXXXXX</developerToken>
          <clientCustomerId>XXX-XXX-XXXX</clientCustomerId>
        </wsdl:RequestHeader>
      </env:Header>
      <env:Body>
        <mutate xmlns="https://adwords.google.com/api/adwords/rm/v201601">
          <operations>
            <ns0:operator>ADD</ns0:operator>
            <operand xsi:type="LogicalUserList">          
              <name>Sample Logical List</name>
              <description>Custom combination list</description>
              <status>OPEN</status>
              <membershipLifeSpan>30</membershipLifeSpan>
              <rules>
                <operator>ANY</operator>
                <ruleOperands>
                  <UserList><id>123456781</id></UserList>
                  <UserList><id>123456782</id></UserList>
                  <UserList><id>123456783</id></UserList>              
                </ruleOperands>
              </rules>
            </operand>
          </operations>
        </mutate>
      </env:Body>
    </env:Envelope>

**Comment by mcloonan** [comment] 2016-03-04 19:32
This SOAP generation is actually wrong (the xsi:type should be explicitly defined for UserList, since there are multiple possible sub-options). This is related to but not exactly the same as issue #75. I will take another look at that and this issue again soon.

**Comment by williambarry007** [comment] 2016-03-04 19:40
Yes, I actually found issue #75 earlier and spoke with the person who posted it before I posted here. In our case, the BasicUserList is what we need, but the UserList seemed to work at least for creating the list.

Thanks for your help!

**Comment by williambarry007** [comment] 2016-03-04 22:22
Why would the xsi:type be affecting the number of rule operands that the API is accepting? I just checked the registry and the max_occurs for UserListLogicalRule rule_operands is unbounded. From google-adwords-api/lib/adwords_api/v201601:

    :UserListLogicalRule=>{
      :fields=>[
        {:name=>:operator, :type=>"UserListLogicalRule.Operator", :min_occurs=>0, :max_occurs=>1}, 
        {:name=>:rule_operands, :type=>"LogicalUserListOperand", :min_occurs=>0, :max_occurs=>:unbounded}
      ]
    },

**Comment by williambarry007** [comment] 2016-03-07 14:30
Is there any kind of workaround that would allow logical list rules to be modified? Can an operation be done directly on a UserListLogicalRule and if so, how would you associate the list ID with it?

**Comment by williambarry007** [comment] 2016-03-08 15:45
I found what may be an underlying issue. I'd expect the XML for the rule operands to be represented like this:

    <rules>
      <operator>ANY</operator>
      <ruleOperands>
        <UserList><id>123456781</id></UserList>
        <UserList><id>123456782</id></UserList>
        <UserList><id>123456783</id></UserList>              
      </ruleOperands>
    </rules>

However, using that way, only the last list is added to the rule. This is the the XML that adds all the lists to the rule:

    <rules>
      <operator>ANY</operator>
      <ruleOperands>
        <UserList><id>123456781</id></UserList>
      </ruleOperands>
      <ruleOperands>
        <UserList><id>123456782</id></UserList>
      </ruleOperands>
      <ruleOperands>
        <UserList><id>123456783</id></UserList>              
      </ruleOperands>
    </rules>

The ruby gem creates XML in the first way, which just doesn't work.

**Comment by mcloonan** [comment] 2016-03-08 15:47
Thank you for this extra investigation. I will tackle all the issues here and from the other issue at once; unfortunately, for now, there is no workaround using the existing Ruby library.

**Comment by williambarry007** [comment] 2016-03-08 16:00
Thank you!

**Comment by dklimkin** [comment] 2016-10-19 14:51
This is a subset of issue #75. The problem of the original request is that xsi:type set is an abstract type. A more specific type must be set, e.g.

:rule_operands => [
          { :xsi_type => "BasicUserList", :id => 123456781 },
        ]

I am closing this one, please follow the root cause bug.

**Closed by dklimkin** 2016-10-19 14:51 UTC
