### ISSUE TITLE
Message: [AuthenticationError.OAUTH_TOKEN_HEADER_INVALID @ ; trigger:'<null>'] when using refresh token

### ISSUE THREAD

**Issue by huydx** [googleads/google-api-ads-ruby#39] opened 2014-12-04 08:12 UTC
Using the example from :
https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201409/misc/create_ad_words_session_without_properties_file.rb

I've got the following error:

```
Message: [AuthenticationError.OAUTH_TOKEN_HEADER_INVALID @ ; trigger:'<null>']
Errors:
    Error [1]:
        field_path:
        trigger: <null>
        error_string: AuthenticationError.OAUTH_TOKEN_HEADER_INVALID
        api_error_type: AuthenticationError
        reason: OAUTH_TOKEN_HEADER_INVALID
        xsi_type: ns2:AuthenticationError
```

However, if I'm authenticate by web and renew the access token by hand, saved to file, everything just going fine.

Can you guy trouble shoot the error.

Thank you very much.

---

Add:

After a while digging the code, I think the reason is that in the sample code:

``` ruby
  adwords = AdwordsApi::Api.new({
    :authentication => {
      :method => 'OAuth2',
      :oauth2_client_id => client_id,
      :oauth2_client_secret => client_secret,
      :developer_token => developer_token,
      :client_customer_id => client_customer_id
      :user_agent => user_agent,
      :oauth2_token => {
        :refresh_token => refresh_token
      }
    },
    :service => {
      :environment => 'PRODUCTION'
    }
  })
```

by setting `oauth2_token => {:refresh_token => refresh_token}`,
it make developer think that implicit setting like this, will make the library to get access token by using refresh token.

But follow the code in [ads-common](https://github.com/googleads/google-api-ads-ruby/blob/master/ads_common/lib/ads_common/auth/oauth2_handler.rb#L82-L84) :

``` ruby
      def get_token(credentials = nil)
        token = super(credentials)
        token = refresh_token! if !@client.nil? && @client.expired?
        return token
      end
```

it only using refresh token when @client nil or expired, and **not** check the credential.

I think the correct behaviour should be: [when refresh token present and access token not, it use refresh token to refresh access token.]

What do you maintainers think about this situation.

If it's fine, i would like to make a pull request

**Comment by kobakei** [comment] 2015-09-30 06:54
I found the same error in https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201506/misc/use_runtime_config.rb
Any update on this issue?

**Comment by mcloonan** [comment] 2015-09-30 13:26
Thank you for the report, and I apologize that this slipped through the cracks. Since it seems @huydx may not be providing the pull request, I'll take a look at implementing a solution myself.

**Comment by offthecuff** [comment] 2015-10-01 13:58
I worked around this by providing an _expires_at_ value in my config. 

The problem is that if the OAuth2 client doesn't have that value it's never going to be considered expired and the access token won't be generated.

**Comment by Gataniel** [comment] 2015-10-01 16:12
@offthecuff Could you please be more specific? What is the exact place where did you provide `expires_at`?

**Comment by offthecuff** [comment] 2015-10-01 16:18
It goes in the `oauth2_token` subsection of the authentication hash. Piggybacking off the example from @huydx , this is what i have:

```ruby
adwords = AdwordsApi::Api.new({
    :authentication => {
      :method => 'OAuth2',
      :oauth2_client_id => client_id,
      :oauth2_client_secret => client_secret,
      :developer_token => developer_token,
      :client_customer_id => client_customer_id
      :user_agent => user_agent,
      :oauth2_token => {
        :refresh_token => refresh_token,
        :expires_at => 0
      }
    },
    :service => {
      :environment => 'PRODUCTION'
    }
  })
```

**Comment by offthecuff** [comment] 2015-10-01 16:29
This is the issue in a nutshell.

[This method will return false if expires_at is nil.](https://github.com/google/signet/blob/master/lib/signet/oauth_2/client.rb#L788)
```ruby
def expired?
        return self.expires_at != nil && Time.now >= self.expires_at
      end
```

[At this point the client is not nil, but it will not be expired either so no token is created.](https://github.com/googleads/google-api-ads-ruby/blob/master/ads_common/lib/ads_common/auth/oauth2_handler.rb#L83)
```ruby
def get_token(credentials = nil)
        token = super(credentials)
        token = refresh_token! if !@client.nil? && @client.expired?
        return token
      end
```

To me this honestly seems like a deficiency in the signet gem, but I suppose this might be the intended behavior.

**Comment by gbailey4** [comment] 2015-12-02 18:51
I've tried the expires_at workaround, but am getting an error at the refresh_token! portion of the code still. Is there any way to get this to work?

**Comment by mcloonan** [comment] 2016-12-16 13:35
Since there's a workaround and the issue seems to be with Signet, I'm going to close this out. It might be worth filing a bug with Signet directly if this is still an issue for you.

**Closed by mcloonan** 2016-12-16 13:35 UTC
