### ISSUE TITLE
Streaming of ads report with Japanese text leads to freeze

### ISSUE THREAD

**Issue by viktorchukhantsev** [googleads/google-api-ads-ruby#147] opened 2018-02-15 15:15 UTC
Stream of ads performance report with Japanese text will lead to 100% CPU load and the code will freeze at some moment.

**Comment by mcloonan** [comment] 2018-02-15 15:28
In the meanwhile, you can try downloading the report using another mechanism.

Can you share the report definition or AWQL query you're using and the CID for the account so that I can attempt to reproduce and troubleshoot?

**Comment by viktorchukhantsev** [comment] 2018-02-20 11:53
The usual download_report mechanism works fine. This bug reproduces only with AWQL in streaming mode.
CID 1597368199
query
`query = 'SELECT Id, AdGroupName, AdGroupId, CampaignId, Description1, ' \
            'Description2, Description, Headline, HeadlinePart1, HeadlinePart2, ' \
            'Path1, Path2, Clicks, Cost, Conversions ' \
            'FROM AD_PERFORMANCE_REPORT ' \
            'WHERE Status IN [ENABLED] AND AdGroupStatus IN [ENABLED] AND ' \
            'CampaignStatus IN [ENABLED] '
`

**Comment by mcloonan** [comment] 2018-02-20 13:34
Thanks for the extra context. I figured the other reporting mechanisms would be unaffected because of the nature of the streaming report. The packets are likely getting broken in the middle of one of the Japanese characters, since they're multiple bytes, which wouldn't be an issue with any of the other download options. I will take a look in more detail as soon as I have a chance.

**Comment by mcloonan** [comment] 2018-09-20 12:16
Closing this as we're not going to be able to fix it in this library. The Google Ads API has support for paging report results which alleviates this issue, so the long-term fix is to move to that API once it's fully launched. In the meanwhile, using a non-streaming report mechanism when the results may include this type of unicode character is recommended.

**Closed by mcloonan** 2018-09-20 12:16 UTC
